In [ ]:
Inatallation of numpy:

In [1]:
!pip install numpy

In [ ]:
Updating numpy:

In [2]:
!pip install numpy --upgrade

  Attempting uninstall: numpy
    Found existing installation: numpy 1.18.5
    Uninstalling numpy-1.18.5:
      Successfully uninstalled numpy-1.18.5


In [ ]:
Data Type in numpy:  array
    Ndarray --> n dimensions.
    Arrays will be considering as Float Datatype.(Decimals)

In [ ]:
Req: create an array from regular python list

In [3]:
import numpy as np    #np --> given as alias name for numpy

In [4]:
array_one = np.array([1,2,3,4,5])
array_one

array([1, 2, 3, 4, 5])

In [5]:
type(array_one)

numpy.ndarray

In [6]:
numbers = [9,8,7,6,5]

array_two = np.array(numbers)
array_two

array([9, 8, 7, 6, 5])

In [ ]:
Req : creation of matrices in mumpy, create an array of zeros

In [8]:
array_of_zeros = np.zeros((3,4))      #(x,y) --> dimensions of matrix x is row, y is column.
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
Req: creation of array of ones

In [9]:
array_of_ones = np.ones((4,4))  #4 rows and 4 columns
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
Req: creation of array without decimals

In [10]:
array_of_ones_int = np.ones((3,3), dtype = np.int16)  #dtype can be int16,int32,int64 can be choosen accordingly how big the number going to be used is.
array_of_ones_int

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)