In [1]:
import numpy as np

In [ ]:
Req : create an empty array

In [2]:
array_empty = np.empty((2,3))

array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
Req: create an identity matrix

In [3]:
array_eye = np.eye(2)

array_eye

array([[1., 0.],
       [0., 1.]])

In [5]:
array_eye = np.eye((5),dtype = np.int32)

array_eye

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
Req: create an even matrix from range 0 to 20   #range is used in list and arange is used in array.

In [9]:
array_of_evens = np.arange(2,20,2)

array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
Req: create an odd matrix from range 0 to 20

In [11]:
array_of_odds = np.arange(1,20,2)

array_of_odds

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])