In [1]:
import numpy as np

In [2]:
array_of_floats = np.arange(0,2,0.3)

array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [3]:
array_2d = np.array([(2,4,6),(3,5,7)])

array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [4]:
array_2d.shape

(2, 3)

In [ ]:
Usage of reshape to create n dimensional matrix

Create an array of 6 numbers

In [5]:
x = np.arange(2,12,2)

x

array([ 2,  4,  6,  8, 10])

In [ ]:
reshape the x matrix into (2,3) matrix

In [7]:
x = np.arange(2,14,2).reshape(2,3)

x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [8]:
x = np.arange(2,14,2).reshape(3,2)

x

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [10]:
x = np.arange(2,14,2).reshape(6,1)

x

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])

In [ ]:
Printing of arrays:

In [11]:
print(x)

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]]


In [13]:
x = np.arange(2,14,2).reshape(3,2)

print(x)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [ ]:
2D array:

In [14]:
a = np.arange(12).reshape(3,4)

print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
3D array:

In [15]:
b = np.arange(24).reshape(2,3,4)

print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
Arithmetic operations in arrays:

In [19]:
even = np.arange(2,22,2)
odd = np.arange(1,20,2)

In [22]:
num = even+odd

print(num)

[ 3  7 11 15 19 23 27 31 35 39]


In [24]:
even-odd

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [25]:
even*odd

array([  2,  12,  30,  56,  90, 132, 182, 240, 306, 380])

In [26]:
even/odd

array([2.        , 1.33333333, 1.2       , 1.14285714, 1.11111111,
       1.09090909, 1.07692308, 1.06666667, 1.05882353, 1.05263158])

In [27]:
even%odd

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)